name: Compile Metrics

on:
  schedule: 
    - cron: '0 0 * * 0' # every week
    - cron: '0 0 31 10 *' # last day of Spooktober
  push: { branches-ignore: [ master ] }
  workflow_dispatch:

env:
  css: |
    @import https://fonts.googleapis.com/css2?family=Roboto&display=swap
    svg {
      color: black;
      font-family: Roboto, sans-serif;
    }
    h1, h2, h3 {
        font-weight: bold;
        color: #3989c5;
    }
    @media (prefers-color-scheme: dark) {
        svg { color: white; }
        h1, h2, h3 { color: #39c5bb; }
    }

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Build base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: base.svg
          base: header, activity, metadata
          extras_js: document.querySelector('footer').innerText = 'Updated on ' + new Date().toISOString().replace(/(T|\.\d+Z)/g,' ')
          extras_css: ${{ env.css }}
          output_action: none

      - name: Build calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: calendar.svg
          base: false
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          extras_css: ${{ env.css }}
          output_action: none

      - name: Get streak
        id: streak
        run: echo "streak=$(python3 streak.py ${{ secrets.METRICS_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Update calender
        run: sudo perl -i -pe "s/(?<=Best streak )\d+/${{ steps.streak.outputs.streak }}/" /metrics_renders/calendar.svg

      - name: Build language
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: language.svg
          base: false
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_categories: programming
          extras_css: ${{ env.css }}
          output_action: none

      - name: Build leetcode
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: leetcode.svg
          base: false
          plugin_leetcode: true
          plugin_leetcode_user: floaterest
          plugin_leetcode_sections: solved, skills, recent
          extras_css: ${{ env.css }}
          output_action: none

      - uses: actions/upload-pages-artifact@v1
        with: { path: /metrics_renders }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
