name: Compile Metrics

on:
  # first day of every month
  # schedule: [{cron: "0 0 1 * *"}]
  push: { branches-ignore: [ master ] }
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: base.svg
      #     base: header, activity, metadata
      #     token: ${{ secrets.METRICS_TOKEN }}

      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: calendar.svg
      #     base: false
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_isocalendar: true
      #     plugin_isocalendar_duration: full-year

      # - run: tree /metrics_renders
      # - uses: actions/upload-pages-artifact@v1
      #   with: { path: /metrics_renders }

      - uses: actions/upload-pages-artifact@v1
        with: { path: . }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
