name: Compile Metrics

on:
  # first day of every month
  # schedule: [{cron: "0 0 1 * *"}]
  push: { branches-ignore: [ master ] }
  workflow_dispatch:

env:
  preset: https://floaterest.github.io/floaterest/preset.yml

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_presets: ${{ env.preset }}
          filename: base.svg
          base: header, activity, metadata

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_presets: ${{ env.preset }}
          filename: calendar.svg
          base: false
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

      - run: sudo cp preset.yml /metrics_renders
      - run: tree /metrics_renders

      - uses: actions/upload-pages-artifact@v1
        with: { path: /metrics_renders }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
