name: Metrics
on:
  # update every day
  schedule: [{cron: "0 4 * * *"}]
  # run workflow manually
  workflow_dispatch:
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics/base.svg
          base: header, activity
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > div{
              border-radius: 1rem;
              background-color: #222222;
              display: grid;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics/calender.svg
          base: false
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest

          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > div{
              border-radius: 1rem;
              background-color: #222222;
              display: grid;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics/languages.svg
          base: false
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest

          plugin_languages: true
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 7
          plugin_languages_limit: 10

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > div{
              border-radius: 1rem;
              background-color: #222222;
              display: grid;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics/activity.svg
          base: false
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest

          plugin_activity: true
          plugin_activity_days: 7
          plugin_activity_load: 100

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > div{
              border-radius: 1rem;
              background-color: #222222;
              display: grid;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics/achievements.svg
          base: false
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest

          plugin_achievements: true
          plugin_achievements_threshold: B
          plugin_achievements_secrets: true

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > div{
              border-radius: 1rem;
              background-color: #222222;
              display: grid;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
