name: Metrics
on:
  # update each hour
  schedule: [{cron: "0 * * * *"}]
  # run workflow manually
  workflow_dispatch:
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/base.svg

          base: header, activity
          
          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject{
              border-radius: 1rem;
            }
            foreignObject > div{
              background-color: #222222;
              padding: 1px;
              height: 100%;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/calender.svg
          base: false

          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject{
              border-radius: 1rem;
            }
            foreignObject > div{
              background-color: #222222;
              padding: 1px;
              height: 100%;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/languages.svg
          base: false

          plugin_languages: true
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 7
          plugin_languages_limit: 10
          commits_authoring: Floaterest

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject{
              border-radius: 1rem;
            }
            foreignObject > div{
              background-color: #222222;
              padding: 1px;
              height: 100%;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: false
          filename: metrics/achievements.svg

          plugin_achievements: true
          plugin_achievements_threshold: B
          plugin_achievements_secrets: true

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject{
              border-radius: 1rem;
            }
            foreignObject > div{
              background-color: #222222;
              padding: 1px;
              height: 100%;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/activity.svg
          base: false

          plugin_activity: true
          plugin_activity_days: 7
          plugin_activity_load: 100

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject{
              border-radius: 1rem;
            }
            foreignObject > div{
              background-color: #222222;
              padding: 1px;
              height: 100%;
            }
            foreignObject > div > section{
              color: #f2f2f2;
            }
